annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Signing Chart
    - kind: added
      description: README.md
    - kind: added
      description: updated to helper-status-checker v4
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
apiVersion: v2
dependencies:
- name: helper-operator
  repository: https://charts.stderr.at/
  version: ~1.0.21
- condition: helper-status-checker.enabled
  name: helper-status-checker
  repository: https://charts.stderr.at/
  version: ~4.0.0
description: Master chart to deploy and configure the Compliance Operator
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/compliance-operator-full-stack
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/compliance-operator.png
keywords:
- security
- compliance
maintainers:
- email: tjungbau@redhat.com
  name: tjungbauer
  url: https://blog.stderr.at/
name: compliance-operator-full-stack
sources:
- https://github.com/tjungbauer/helm-charts
- https://charts.stderr.at/
- https://github.com/tjungbauer/openshift-clusterconfig-gitops
version: 1.0.27
