    helper-operator:
      operators:
        compliance-operator:
          enabled: true
          syncwave: '0'
          namespace:
            name: openshift-compliance
            create: true
          subscription:
            channel: release-0.1
            approval: Manual
            operatorName: compliance-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          operatorgroup:
            create: true
            notownnamespace: true
 helper-status-checker:
      enabled: true 
      approver: true 
      operatorName: compliance-operator 
      namespace:
        name: openshift-compliance 
      serviceAccount: 
        create: true
        name: "sa-compliance" 
 compliance:
      scansettingbinding:
        enabled: true
        syncwave: '3' 
        profiles: 
          - name: ocp4-cis-node
          - name: ocp4-cis
        scansetting: default
